COMPONENT_NAME=ingestbot_cdk
include ../../python/Makefile.base

# Freeze CDK bootstrap template (infrequent)
bootstrap-template:
	cdk bootstrap --show-template > ingestbot_cdk/bootstrap/template.yml
