name: python
on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/python.yml
        with:
          component_name: ingestion_api
