# Workflow for pull requests and merges to master
name: root-integrate
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  prelude-test:
    uses: ./.github/workflows/sub-python-test.yml
    with:
      component_name: ibot_prelude
  api-test:
    uses: ./.github/workflows/sub-python-test.yml
    with:
      component_name: ibot_api
  cdk-test:
    uses: ./.github/workflows/sub-python-test.yml
    with:
      component_name: ibot_cdk
