# Workflow for deployments to the dev envrionment
name: root-deploy-dev
on:
  push:
    branches:
    - deploy-dev
jobs:
  cdk-artifact:
    uses: ./.github/workflows/sub-python-artifact.yml
    with:
      component_name: ibot_cdk
  api-artifact:
    uses: ./.github/workflows/sub-python-artifact.yml
    with:
      component_name: ibot_api
  cdk-deploy:
    needs: [cdk-artifact, api-artifact]
    uses: ./.github/workflows/sub-cdk-deploy.yml
    with:
      env: dev
    # NOTE: inheriting secrets is the only way to make env secrets work with reusable workflows.
    secrets: inherit
