# Workflow for deployments to the dev envrionment
name: root-deploy-dev
on:
  push:
    branches:
    - deploy-dev
jobs:
  cdk-deploy:
    uses: ./.github/workflows/sub-cdk-deploy.yml
    with:
      env: dev
