# Workflow for deployments to the dev envrionment
name: merge
on:
  push:
    branches:
    - deploy-dev
jobs:
  integrate:
    uses: ./.github/workflows/root-integrate.yml
  cdk-deploy:
    needs: [integrate]
    uses: ./.github/workflows/sub-cdk-deploy.yml
    with:
      env: dev
