# Workflow for pull requests and merges to master
name: root-integrate
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  integrate:
    uses: ./.github/workflows/sub-integrate.yml
