# Publishes an artifact for the given python component
name: sub-python-artifact
on:
  workflow_call:
    inputs:
      component_name:
        type: string
        required: true
jobs:
  # Build and store the artifact
  artifact:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install utils
        run: pip3 install --upgrade pip setuptools wheel
      - name: Cache pipcache
        uses: actions/cache@v3
        with:
          path: .pipcache
          key: ${{ runner.os }}-pipcache
      - name: Package project
        working-directory: components/${{ inputs.component_name }}
        run: make package
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.component_name }}_artifact
          path: .build/${{ inputs.component_name }}.zip
