# TEST
name: sub-test-env
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
jobs:
  test:
    # environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Test env
        run: echo "Test var <$TEST_VAR> - global var <$GLOBAL_VAR>"
        env:
          TEST_VAR: ${{ secrets.TEST_VAR }}
          GLOBAL_VAR: ${{ secrets.GLOBAL_VAR }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Cat env
        run: cat /home/runner/work/_temp/_runner_file_commands/set_env_*
