# Deploys to the given environment
name: sub-cdk-deploy
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      env_title:
        type: string
        required: true
jobs:
  # Deploy with CDK
  deploy:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    container:
      image: python:3.9.13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install utils
        run: /bin/bash support/docker/setup.sh
      - name: Create directories
        run: mkdir -p .artifacts .build
      # Github "helpfully" adds unnecessary structure to artifacts so there's some work to be done
      - name: Download cdk artifact
        uses: actions/download-artifact@v3
        with:
          name: ibot_cdk_artifact
          path: .artifacts/ibot_cdk_artifact
      - name: Download api artifact
        uses: actions/download-artifact@v3
        with:
          name: ibot_api_artifact
          path: .artifacts/ibot_api_artifact
      - name: Move artifacts
        run: mv ../.artifacts/ibot_cdk_artifact/ibot_cdk.zip . && mv ../.artifacts/ibot_api_artifact/ibot_api.zip .
        working-directory: .build
      - name: Extract cdk code
        run: unzip ibot_cdk.zip -d ibot_cdk
        working-directory: .build
      - name: Debug cdk
        run: pwd && ls -lash .
        working-directory: .build/ibot_cdk
      - name: Deploy api
        run: bash -c 'source ../../scripts/source_deploy.sh && ibot_assume_deploy_role ${{ inputs.env }} ci && aws sts get-caller-identity && ./entrypoint.sh deploy -e Ibot${{ inputs.env_title }}ApiStack'
        working-directory: .build/ibot_cdk
        env:
          IBOT_ENV: ${{ inputs.env }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
