# Deploys to the given environment
name: sub-cdk-deploy
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
jobs:
  # Deploy with CDK
  deploy:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    container:
      image: python:3.9.13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache pipcache
        uses: actions/cache@v3
        with:
          path: .pipcache
          key: ${{ runner.os }}-pipcache
      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: components/ibot_cdk/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('components/ibot_cdk/dev-requirements.txt') }}
      - name: Build cdk component
        working-directory: components/ibot_cdk
        run: make build
      # TODO add CDK invocation
